// Strings for the open-source shell. The reused AwwO components keep their own catalog
// (canvas/i18n.tsx); this one covers only what this edition adds around them.
import type { UiLocale } from './locale';

const EN = {
  brand: 'AwwO Canvas',
  edition: 'open source',
  runtimesReady: '{count} runtime(s) ready',
  runtimesNone: 'No runtime ready',
  runtimesOffline: 'Orchestrator offline',
  openRuntimes: 'Runtimes',
  assistantToggle: 'Assistant',
  language: '中文',
  canvasMenu: 'Canvas',
  importJson: 'Import JSON…',
  exportJson: 'Export JSON',
  exampleWorkflow: 'Example: plan → write → review',
  exampleReview: 'Example: review loop (2 rounds)',
  exampleTeam: 'Example: software team (5 nodes)',
  newCanvas: 'Clear the canvas',
  importFailed: 'That file is not an AwwO Canvas document.',
  corrupt: 'The saved canvas could not be read. Its raw text was kept under awwo.canvas.v2.corrupt in local storage.',
  run: 'Run graph',
  runSelection: 'Run {count} selected',
  stop: 'Stop',
  stopping: 'Stopping…',
  runQueued: 'Queued…',
  runRunning: 'Running · {done}/{total} done',
  runRound: 'Round {round}',
  runCompleted: 'Completed · {done} done',
  runFailed: 'Finished with problems · {done} done · {failed} failed · {blocked} blocked',
  runCancelled: 'Stopped',
  runApproved: 'Approved after {rounds} round(s)',
  runExhausted: 'Not approved within {rounds} round(s)',
  cached: '{count} reused',
  noRuntime: 'No runtime is ready. Start a worker (npm run worker:mock) or plug one in under Runtimes.',
  addNode: 'Add a node',
  addForm: 'Requirement form',
  addTeamTemplate: 'Software team (5 nodes)',
  configure: 'Configure',
  delete: 'Delete',
  runNode: 'Run',
  viewOutput: 'View',
  output: 'Output',
  partial: 'Partial (run failed)',
  noOutput: 'No output yet',
  defaultRuntime: 'Default runtime',
  defaultModel: 'Runtime default',
  team: 'Team · {count}',
  formFields: '{count} field(s)',
  inspectorTitle: 'Node settings',
  close: 'Close',
  title: 'Title',
  runtime: 'Runtime',
  model: 'Model',
  effort: 'Reasoning effort',
  effortDefault: 'Model default',
  persona: 'Persona and instructions',
  inputs: 'Inputs',
  outputs: 'Outputs',
  chat: 'Talk to this node',
  chatHint: 'A chat message is sent as written, with the persona as instructions. It never replaces the node output; Run does that.',
  chatEmpty: 'No messages yet.',
  chatClear: 'Clear conversation',
  wiredFrom: 'from {title}',
  formFieldLabel: 'Label',
  formFieldValue: 'Value',
  addField: 'Add field',
  removeField: 'Remove field',
  unavailableRuntime: '{id} (unavailable)',
  deliverable: 'Output of {title}',
  copy: 'Copy',
  copied: 'Copied',
  download: 'Download',
  rawOutput: 'Raw output',
  teamTurns: 'Team turns',
  outputInvalid: 'The output does not match the contract:',
  runtimesTitle: 'Hot-plug runtimes',
  runtimesIntro: 'A runtime is any worker that speaks the worker protocol. Plug one in here, list it in runtimes.json, or start a worker with AWWO_REGISTER_URL to register itself. Runs that already started keep the runtime and model they were admitted with.',
  probe: 'Re-check',
  remove: 'Unplug',
  fromFile: 'runtimes.json',
  fromApi: 'plugged in',
  models: 'Models',
  tools: 'Tools',
  load: 'Load {active}/{max}',
  addRuntime: 'Plug in a runtime',
  runtimeId: 'Id',
  runtimeUrl: 'Worker URL',
  runtimeLabel: 'Label',
  runtimeToken: 'Bearer token (optional)',
  plugIn: 'Plug in',
  apiToken: 'Orchestrator token',
  apiTokenHint: 'Only needed when the orchestrator runs with AWWO_API_TOKEN. Stored in this browser.',
  save: 'Save',
  planner: 'Planner: {runtime} · {model}',
  defaultRuntimeInfo: 'Default runtime: {runtime} · {model}',
  plannerUnavailable: 'No runtime is ready to plan.',
  taskRunning: 'Working…',
  taskStopped: 'Stopped',
  taskFailed: 'Failed: {error}',
  taskStop: 'Stop',
  undone: 'The plan was undone.',
  planBusy: 'A graph run is in progress. Plan again once it has finished.',
  planCancelled: 'Planning stopped. The canvas was not changed.',
  taskInterrupted: 'The connection ended before the task finished.',
  emptyHint: 'Describe what you want to build, or right-click the canvas to add a node.',
} as const;

export type ShellTextKey = keyof typeof EN;

const ZH: Record<ShellTextKey, string> = {
  brand: 'AwwO Canvas',
  edition: '开源版',
  runtimesReady: '{count} 个运行时就绪',
  runtimesNone: '没有就绪的运行时',
  runtimesOffline: '编排服务未连接',
  openRuntimes: '运行时',
  assistantToggle: '助手',
  language: 'EN',
  canvasMenu: '画布',
  importJson: '导入 JSON…',
  exportJson: '导出 JSON',
  exampleWorkflow: '示例：规划 → 撰写 → 验收',
  exampleReview: '示例：互审循环（2 轮）',
  exampleTeam: '示例：软件团队（5 个节点）',
  newCanvas: '清空画布',
  importFailed: '这个文件不是 AwwO Canvas 文档。',
  corrupt: '已保存的画布无法读取，原始内容保存在本地存储 awwo.canvas.v2.corrupt 中。',
  run: '运行整图',
  runSelection: '运行选中的 {count} 个',
  stop: '停止',
  stopping: '正在停止…',
  runQueued: '排队中…',
  runRunning: '运行中 · 已完成 {done}/{total}',
  runRound: '第 {round} 轮',
  runCompleted: '已完成 · {done} 个节点',
  runFailed: '运行结束但有问题 · 完成 {done} · 失败 {failed} · 阻塞 {blocked}',
  runCancelled: '已停止',
  runApproved: '第 {rounds} 轮评审通过',
  runExhausted: '{rounds} 轮内未通过评审',
  cached: '复用 {count} 个',
  noRuntime: '没有就绪的运行时。先启动一个 worker（npm run worker:mock），或在「运行时」里接入。',
  addNode: '添加节点',
  addForm: '需求表单',
  addTeamTemplate: '软件团队（5 个节点）',
  configure: '配置',
  delete: '删除',
  runNode: '运行',
  viewOutput: '查看',
  output: '产出',
  partial: '部分产出（运行失败）',
  noOutput: '还没有产出',
  defaultRuntime: '默认运行时',
  defaultModel: '运行时默认模型',
  team: '团队 · {count}',
  formFields: '{count} 个字段',
  inspectorTitle: '节点设置',
  close: '关闭',
  title: '标题',
  runtime: '运行时',
  model: '模型',
  effort: '思考强度',
  effortDefault: '模型默认',
  persona: '角色与指令',
  inputs: '输入',
  outputs: '输出',
  chat: '与这个节点对话',
  chatHint: '对话消息按原样发送，角色设定作为指令；对话不会覆盖节点产出，运行才会。',
  chatEmpty: '还没有消息。',
  chatClear: '清空对话',
  wiredFrom: '来自「{title}」',
  formFieldLabel: '名称',
  formFieldValue: '内容',
  addField: '添加字段',
  removeField: '删除字段',
  unavailableRuntime: '{id}（不可用）',
  deliverable: '「{title}」的产出',
  copy: '复制',
  copied: '已复制',
  download: '下载',
  rawOutput: '原始输出',
  teamTurns: '团队成员发言',
  outputInvalid: '产出不符合输出契约：',
  runtimesTitle: '热插拔运行时',
  runtimesIntro: '运行时就是任何实现了 worker 协议的进程。可以在这里接入、写进 runtimes.json，或用 AWWO_REGISTER_URL 让 worker 启动时自行注册。已开始的运行会继续使用准入时冻结的运行时和模型。',
  probe: '重新检查',
  remove: '拔出',
  fromFile: 'runtimes.json',
  fromApi: '运行中接入',
  models: '模型',
  tools: '工具',
  load: '负载 {active}/{max}',
  addRuntime: '接入运行时',
  runtimeId: 'ID',
  runtimeUrl: 'Worker 地址',
  runtimeLabel: '名称',
  runtimeToken: 'Bearer token（可选）',
  plugIn: '接入',
  apiToken: '编排服务 token',
  apiTokenHint: '仅当编排服务设置了 AWWO_API_TOKEN 时需要，保存在当前浏览器。',
  save: '保存',
  planner: '规划：{runtime} · {model}',
  defaultRuntimeInfo: '默认运行时：{runtime} · {model}',
  plannerUnavailable: '没有可用于规划的运行时。',
  taskRunning: '执行中…',
  taskStopped: '已停止',
  taskFailed: '失败：{error}',
  taskStop: '停止',
  undone: '方案已撤销。',
  planBusy: '整图正在运行，结束后再规划。',
  planCancelled: '已停止规划，画布没有改动。',
  taskInterrupted: '任务完成前连接中断了。',
  emptyHint: '描述你想做的事，或在画布上右键添加节点。',
};

const CATALOG: Record<UiLocale, Record<ShellTextKey, string>> = { en: EN, zh: ZH };

export type ShellTranslate = (key: ShellTextKey, values?: Record<string, string | number>) => string;

export function shellText(locale: UiLocale): ShellTranslate {
  return (key, values = {}) => CATALOG[locale][key].replace(/\{(\w+)\}/g, (token, name: string) =>
    Object.hasOwn(values, name) ? String(values[name]) : token);
}
